project_name: Network Discovery tool
builds:
   - env:
        - CGO_ENABLED=0
     goos:
        - linux
     goarch:
        - amd64

archive:
   format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
       - '^docs:'
       - '^doc:'
       - '^test:'

dockers:
   - image: cycoresystems/netdiscover
     tag_templates:
        - "{{ .Tag }}"
        - "v{{ .Major }}"
        - "v{{ .Major }}.{{ .Minor }}"
        - latest
