project_name: Network Discovery tool
builds:
  - binary: netdiscover
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
   - id: netdiscover
     format: binary
     name_template: "{{ .Binary }}.{{ .Os }}.{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^test:'

dockers:
  - image_templates:
    - "cycoresystems/netdiscover:{{ .Tag }}"
    - "cycoresystems/netdiscover:v{{ .Major }}"
    - "cycoresystems/netdiscover:v{{ .Major }}.{{ .Minor }}"
    - "cycoresystems/netdiscover:latest"
